### ISSUE TITLE
Access forbidden!

### ISSUE THREAD

**Issue by ghost** [ServerPress/catalina-fix#2]
Hi
I can the script but get this message in firefox browser.
Thanks
Scott

Access forbidden!

You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.

If you think this is a server error, please contact the webmaster.
Error 403
www.mackiedesigncompany-nov2019.dev.cc
Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/7.1.13 mod_perl/2.0.8-dev Perl/v5.16.3

**Comment by GreggFranklin** [comment]
Hello Scott,

Please download the latest version of DesktopServer v3.9.4 as it should resolve this issue and does not require the Catalina fix script. Also for quicker response please use the support@serverpress.com email as that comes into our support ticketing system.
